# This file was generated by GoReleaser. DO NOT EDIT.
class Statiks < Formula
  desc "Fast, zero-configuration, static HTTP filer server."
  homepage "https://github.com/janiltonmaciel/statiks"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/janiltonmaciel/statiks/releases/download/1.0.0/statiks_1.0.0_darwin_amd64.tar.gz"
    sha256 "a85d2bfcc99e446774cfe8a108e396c307c9e81f648fa4382260218f975f500c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/janiltonmaciel/statiks/releases/download/1.0.0/statiks_1.0.0_linux_amd64.tar.gz"
      sha256 "d9c2308f0bf4d8158e8a3ac3921f2b0a87f13201e872892dfa04ba2a588b6d42"
    end
  end

  def install
    bin.install "statiks"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statiks --version")
  end
end
