# This file was generated by GoReleaser. DO NOT EDIT.
class Statiks < Formula
  desc "Fast, zero-configuration, static HTTP filer server."
  homepage "https://github.com/janiltonmaciel/statiks"
  version "1.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/janiltonmaciel/statiks/releases/download/v1.3.0/statiks_1.3.0_darwin_amd64.tar.gz"
    sha256 "e92231744a698cbf0b9a5ed5db68b63978e1395c4cbab794d791517704b5554a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/janiltonmaciel/statiks/releases/download/v1.3.0/statiks_1.3.0_linux_amd64.tar.gz"
      sha256 "d7c9410e4a986250ed19e00de806b7819368373f8e2cfc659573828ab12aeb07"
    end
  end

  def install
    bin.install "statiks"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/statiks --version")
  end
end
